services:
  - type: web
    name: boiler-crm-app
    env: node
    buildCommand: npm install
    startCommand: node index.js   # <-- this is the fix
    envVars:
      - key: NODE_ENV
        value: production
